version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: "Greenweeze sales data"
        loaded_at_field: "cast(date_date as timestamp)"
        freshness:
          warn_after: {count: 90, period: day}
        tests:
           - unique: 
              column_name: "orders_id || pdt_id"
        columns: 
          - name: date_date
            description: "date of order"
          - name: orders_id
            description: "unique id for each order"
            tests:
              - not_null
          - name: pdt_id
            description: "unique id for each product"
            tests:
              - not_null
      - name: product
        identifier: raw_gz_product
        description: "Greenweeze product information inlc price"
        columns:
          - name: products_id
            description: "unique product id"
            tests: 
              - not_null
              - unique
      - name: ship
        identifier: raw_gz_ship
        description: "Greenweeze shipping information"
        columns: 
          - name: orders_id
            description: "id for each order"
            tests: 
              - not_null
              - unique
      - name: adwords
        identifier: raw_gz_adwords
        description: "Greenweeze adwords ad data"
      - name: bing
        identifier: raw_gz_bing
        description: "Greenweeze bing ads data"
      - name: criteo
        identifier: raw_gz_criteo
        description: "Greenweeze criteo ads data"
      - name: facebook 
        identifier: raw_gz_facebook
        description: "Greenweeze facebook ads data"
       
models: 
  - name: int_orders_margin
    description: "overview of margin per sale"
    columns: 
      - name: orders_id
        description: "unique orders id"
        tests: 
          - unique
          - not_null
  - name: int_sales_margin
    description: "sales figures"
    tests:
      - unique: 
              column_name: "orders_id || products_id"
    columns: 
      - name: orders_id
        description: "unique orders"
        tests: 
          - not_null
      - name: products_id
        description: "unique products id"
        tests: 
          - not_null 
  - name: int_orders_operational
    description: "operational margin per order"
    columns: 
      - name: orders_id
        description: "unique orders id"
        tests: 
          - not_null
          - unique
  - name: finance_days
    description: "overview of metrics per day"
    columns: 
      - name: date_date
        description: "every day is new entry"
        tests: 
          - not_null
          - unique


